experiment_name: urbanbis/yingrenshi_large_scene   # dataset/testname
parents:
  - config/urbanbis/yingrenshi_large_scene/dataset.yml
  - config/urbanbis/yingrenshi_large_scene/level_of_gaussian.yml
  - config/urbanbis/yingrenshi_large_scene/stage_8_4.yml

exp: output/urbanbis/yingrenshi_large_scene/log
gpus: [0]

log_interval: 1_000
save_interval: 100_000

max_steps: 750

RGB_RENDER_L1_SSIM:
  module: LoG.render.renderer.NaiveRendererAndLoss
  args:
    use_origin_render: False
    use_randback: True

train:
  dataset: $dataset
  render: $RGB_RENDER_L1_SSIM
  stages: $NAIVE_STAGE
  init:
    method: scale_min
    dataset_state:
      scale: 4

val:
  dataset: $val_dataset
  iteration: 10000